# Generated by Django 6.0.2 on 2026-02-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_collaboration_validee', models.BooleanField(default=False, help_text="Indique qu'une collaboration réelle a été confirmée")),
                ('message', models.TextField(blank=True, null=True)),
                ('duree_estimee_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ENVOYE', 'Contact partagé'), ('MISSION_CONFIRME', 'Mission confirmée'), ('SANS_SUITE', 'Sans suite'), ('REFUSE', 'Refus du consultant')], default='ENVOYE', max_length=30)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('date_suivi_prevu', models.DateTimeField(blank=True, null=True)),
                ('suivi_envoye', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_clients', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_consultant', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='missions.mission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mission', 'consultant'), name='unique_contact_per_mission_consultant')],
            },
        ),
    ]
