# Generated by Django 6.0.2 on 2026-02-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='date_suivi_reel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='suivi_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='statut',
            field=models.CharField(choices=[('ENVOYE', 'Contact partagé'), ('MISSION_CONFIRME', 'Mission confirmée'), ('MISSION_TERMINEE', 'Mission terminée'), ('SANS_SUITE', 'Sans suite'), ('REFUSE', 'Refus du consultant')], default='ENVOYE', max_length=30),
        ),
    ]
