# Generated by Django 6.0.2 on 2026-02-14 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(fields=('mission', 'consultant'), name='unique_contact_per_mission_consultant'),
        ),
    ]
