# Generated by Django 6.0.2 on 2026-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_contactrequest_unique_contact_per_mission_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='est_collaboration_validee',
            field=models.BooleanField(default=False, help_text="Indique qu'une collaboration réelle a été confirmée"),
        ),
    ]
