# Generated by Django 6.0.2 on 2026-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Administrateur Système'), ('BUREAU', 'Membre du Bureau / Conseil'), ('COMPTA', 'Comptabilité / Trésorerie'), ('SECRETARIAT', 'Secrétariat Administratif'), ('MEMBER', 'Membre Adhérent'), ('CONSULTANT', 'Expert Roster'), ('CLIENT', 'Institution / Recruteur')], default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
