# Generated by Django 6.0.2 on 2026-02-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_membre_association',
        ),
    ]
