# Generated by Django 6.0.2 on 2026-02-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_id_membre_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_membre_association',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
