# Generated by Django 6.0.2 on 2026-02-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_id_membre_association'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Administrateur Système'), ('BUREAU', 'Membre du Bureau / Conseil'), ('COMPTA', 'Comptabilité'), ('SECRETARIAT', 'Secrétariat Administratif'), ('MEMBER', 'Membre Adhérent'), ('CONSULTANT', 'Expert Roster'), ('CLIENT', 'Institution / Recruteur')], default='CLIENT', max_length=20),
        ),
    ]
