# Generated by Django 6.0.2 on 2026-02-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
