# Generated by Django 6.0.2 on 2026-02-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_consultantprofile_motif_refus'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
